files:
  - source: /packages/localization/src/config/translations.json
    translation: /apps/web/public/locales/%locale%.json
pull_request_title: 'chore: New Crowdin updates'
commit_message: '[ci skip]'
