name: 🐞 Bug Report
description: File a bug/issue
title: '[BUG] <title>'
labels: [Bug, Triage]
assignees:
  - Chef-Cheems
  - chef-jojo
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true
  - type: dropdown
    attributes:
      label: Product
      description: Which page or product does this relate to?
      multiple: false
      options:
        - Trade
        - Farms
        - Syrup Pools
        - Lottery
        - Prediction
        - IFO
        - Info
        - NFT
        - Other
    validations:
      required: true
  - type: textarea
    attributes:
      label: Current Behavior
      description: A concise description of what you're experiencing.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Environment
      description: |
        example 1:
          - **Device**: MacBook Pro
          - **OS**: Big Sur 11.3.1
          - **Brower**: Chome
          - **Wallet**: Metamask

        example 2:
          - **Device**: IPhone XR
          - **OS**: IOS 13
          - **Brower**: N/A
          - **Wallet**: Metamask app
      value: |
        - Device:
        - OS:
        - Browser:
        - Wallet:
      render: markdown
    validations:
      required: true
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
