name: Fetch and update Aptos LP APRs

on:
  workflow_dispatch:
  schedule:
    # 23:15 UTC
    # GitHub Actions might be delayed if time is at exact hour
    - cron: "15 23 * * *"

jobs:
  updateLPsAPRs:
    runs-on: ubuntu-latest
    if: github.repository == 'pancakeswap/pancake-frontend'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Fetch and save Aptos LP APR data
        run: yarn updateAptosLPsAPR

      - name: Format
        run: yarn prettier --write "apps/aptos/config/constants/lpAprs/*.{ts,json}"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          author: PancakeSwap Bot <pancakeswap-bot@protonmail.com>
          token: ${{ secrets.LP_APR_PANCAKE_BOT }}
          delete-branch: true
          commit-message: "chore: Update Aptos LP APRs for Farms"
          title: "chore: Update Aptos LP APRs for Farms"
          body: |
            - Update Aptos LP APRs for Farms

            Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          labels: automerge
          branch: update-aptos-lp-aprs-for-farms
